# Generated by Django 3.1.5 on 2021-01-20 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AddField(
            model_name='euser',
            name='birth_day',
            field=models.DateField(default=datetime.date(1900, 1, 1), verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='euser',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Отчество'),
        ),
    ]
